"""add column active to countries

Revision ID: dab29a34f745
Revises: 72e9b7ea8cc0
Create Date: 2021-12-18 15:59:46.635964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dab29a34f745'
down_revision = '72e9b7ea8cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('active', sa.Boolean(), nullable=False, default=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'active')
    # ### end Alembic commands ###
