"""add transaction-images table

Revision ID: f21ad7965c1a
Revises: 39389c70a205
Create Date: 2021-12-16 21:35:28.154461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21ad7965c1a'
down_revision = '39389c70a205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction-images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('image_file_name', sa.String(length=80), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.add_column('transactions', sa.Column('transaction_amount', sa.Float(), nullable=False))
    op.add_column('transactions', sa.Column('transaction_date', sa.String(length=80), nullable=False))
    op.drop_constraint('transactions_transaction_name_key', 'transactions', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('transactions_transaction_name_key', 'transactions', ['transaction_name'])
    op.drop_column('transactions', 'transaction_date')
    op.drop_column('transactions', 'transaction_amount')
    op.drop_table('transaction-images')
    # ### end Alembic commands ###
